default: &default
  adapter: postgresql
  username: wing_clip
  password:
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 16) %>

development:
  <<: *default
  database: wing_clip_development

test:
  <<: *default
  database: wing_clip_test

production:
  url: <%= ENV.fetch('DATABASE_URL', '') %>
